##########################################
# Config du plugin AutomatedOpenUHC      #
##########################################

# Minimum players to run the game
min-players: 5

# Countdown before game start when min-players is reached
countdown: 180

language: en

bungeecord:
   enable: false # Set true if you use bungee cord proxy. It will move all players to "move-to" server after "move-after" seconds
   move-to: lobby
   move-after: 60

restart:
   enable: true
   restart-after: 65

